"""Version-token guardrail (#1279; epic .github#280, spec §2 goal 4 and §6).

OS version tokens (``ubuntu24``, ``noble``, ``rhel9``, ``el9``, and the 26/10 forms) are
written by hand in exactly one place: the catalog, ``lab/versions.yaml``. Everything
else resolves them through ``mqlab.versions``; box names such as ``<role>-<os><major>``
are GENERATED by the resolver and so must never appear as literals in the code either.

The scan covers the runtime roots (``src/``, ``lab/``, ``ansible/``, ``scripts/``).
``docs/`` and ``tests/`` are out of scope. Exempt are only the files that exist
precisely to differ by version:

- ``lab/versions.yaml`` — the catalog;
- ``src/mqlab/retired_boxes.py`` — the retired-names table (spec §4.9);
- ``lab/boxes/rhel/ks*.cfg`` — the per-major kickstart files;
- ``ansible/**/vars/<Distribution>-<major>.yml`` — the per-version vars files.

A hit is fixed at its source (reword the comment version-neutrally, or resolve the name
through the catalog). Never widen the exemptions to silence a real hit.

Modelled on the logsearch-ref guardrail (f0b86c2), including its exclusion of compiled
Python artifacts: a stale ``__pycache__/*.pyc`` must never false-trip the scan (#1184).
"""

from __future__ import annotations

import re
from fnmatch import fnmatchcase
from pathlib import Path

from mqlab.paths import repo_root

# OS-version tokens only, case-sensitive. Deliberately NOT bare "9.6"/"2404", which
# collide with unrelated software versions and ports. Prose such as "RHEL 9" or
# "Ubuntu 24.04" (capitalised, space-separated) is not a token and does not match.
TOKENS = re.compile(
    r"\b(ubuntu-?2[46](\.?04)?|noble|resolute|rhel-?(9|10)(\.\d+)?|rhel/(9|10)|el(9|10))\b"
)

SCAN = ("src", "lab", "ansible", "scripts")

EXEMPT = frozenset(
    {
        Path("lab/versions.yaml"),  # the catalog
        Path("src/mqlab/retired_boxes.py"),  # the retired-names table (spec §4.9)
    }
)

# ansible/**/vars/<Distribution>-<major>.yml, e.g. roles/rdqm-install/vars/RedHat-9.yml.
_PER_VERSION_VARS = re.compile(r"[A-Za-z]+-\d+\.yml")


def _is_exempt(rel: Path) -> bool:
    """True iff ``rel`` (repo-relative) is a file that exists to differ by version."""
    if rel in EXEMPT:
        return True
    if rel.parent == Path("lab/boxes/rhel") and fnmatchcase(rel.name, "ks*.cfg"):
        return True  # per-major kickstart
    return (
        rel.parts[0] == "ansible"
        and rel.parent.name == "vars"
        and _PER_VERSION_VARS.fullmatch(rel.name) is not None
    )


def _scanned_files(repo: Path) -> list[Path]:
    """Every source/config file under the scanned roots, minus compiled artifacts."""
    files: list[Path] = []
    for root in SCAN:
        for path in sorted((repo / root).rglob("*")):
            if not path.is_file():
                continue
            if "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}:
                continue
            files.append(path)
    return files


def scan(repo: Path) -> list[str]:
    """``path:line: text`` for every OS version token outside the exempt files."""
    hits: list[str] = []
    for path in _scanned_files(repo):
        rel = path.relative_to(repo)
        if _is_exempt(rel):
            continue
        for lineno, line in enumerate(path.read_text(errors="ignore").splitlines(), start=1):
            if TOKENS.search(line):
                hits.append(f"{rel}:{lineno}: {line.strip()}")
    return hits


def test_no_os_version_tokens_outside_the_catalog():
    hits = scan(repo_root())
    assert hits == [], (
        "OS version tokens outside lab/versions.yaml (epic .github#280) — fix each at its "
        "source (reword version-neutrally, or resolve through mqlab.versions):\n" + "\n".join(hits)
    )


def test_scan_reads_the_repo_and_skips_compiled_artifacts():
    scanned = _scanned_files(repo_root())
    assert scanned, "version-token scan returned no files — scanned roots mis-resolved?"
    assert all(
        "__pycache__" not in p.parts and p.suffix not in {".pyc", ".pyo"} for p in scanned
    ), "the scan must exclude compiled Python artifacts (#1184)"


def test_token_matcher_catches_os_tokens_only():
    for token in (
        "infra-ubuntu24",
        "ubuntu-24.04",
        "ubuntu2404",
        "mq-client-ubuntu26",
        "noble",
        "resolute",
        "mq-rdqm-rhel9",
        "rhel-9.6-x86_64-dvd.iso",
        "rhel/10-x86_64",
        "PreReqs/el9/",
        "kmod el10",
    ):
        assert TOKENS.search(token), f"{token!r} must trip the guardrail"
    for benign in (
        "RHEL 9 does not ship systemd-resolved",  # guest-rendered prose, not a token
        "Ubuntu 24.04's stock timer",
        "pymqi 9.6",
        "port 2404",
        "noblesse",
        "the infra box",
        "nativeha-rhel-crr",
    ):
        assert not TOKENS.search(benign), f"{benign!r} must not trip the guardrail"


def test_scan_catches_a_token_and_honours_the_scope(tmp_path):
    # Negative control: a planted token in a scanned root is caught; the same token in
    # an exempt file, an out-of-scope root, or a compiled artifact is not.
    planted = tmp_path / "ansible" / "roles" / "demo" / "tasks" / "main.yml"
    planted.parent.mkdir(parents=True)
    planted.write_text("---\n# boots the mq-rdqm-rhel9 box\n")
    for exempt in (
        "lab/versions.yaml",
        "src/mqlab/retired_boxes.py",
        "lab/boxes/rhel/ks.cfg",
        "ansible/roles/demo/vars/RedHat-9.yml",
        "src/mqlab/__pycache__/x.cpython-312.pyc",
        "scripts/stale.pyc",
        "docs/notes.md",
        "tests/test_x.py",
    ):
        path = tmp_path / exempt
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("rhel9 noble ubuntu24\n")
    (tmp_path / "lab" / "boxes" / "rhel" / "await.sh").write_text("# fine\n")
    hits = scan(tmp_path)
    assert hits == ["ansible/roles/demo/tasks/main.yml:2: # boots the mq-rdqm-rhel9 box"]


def test_vars_exemption_is_per_version_files_only():
    assert _is_exempt(Path("ansible/roles/drbd-san/vars/Ubuntu-24.yml"))
    assert not _is_exempt(Path("ansible/vars/pki-entities.yml"))  # not <Distro>-<major>
    assert not _is_exempt(Path("ansible/roles/x/defaults/RedHat-9.yml"))  # not vars/
    assert not _is_exempt(Path("lab/vars/RedHat-9.yml"))  # not under ansible/
    assert not _is_exempt(Path("lab/boxes/ubuntu/ks.cfg"))  # kickstarts: rhel only
