"""Render BIND9 config + zone files from the DNS records (#476, epic .github#21).

Consumes ``mqlab.dns`` records and serializes them to the artifacts the
``bind-dns`` role copies onto the infra nodes: one zone file per forward/reverse
zone, and — per infra node — the ``named.conf.options`` and ``named.conf.local``
it needs (which zones it masters, where it forwards the rest).

Authority model (resolves the reverse-zone question the spec left to this role):
the **client-org** infra node is authoritative for ``client.com`` *and every
reverse zone* — our estate owns most addresses, including the shared ``net-ext``
``/24``. The **service-org** infra node is authoritative only for ``service.com``.
Each node forwards everything it does not master to its peer over ``net-ext``
(``forward only``), so the two zones resolve across the org boundary.

The rendered files are pure functions of the topology (no timestamps), so a
re-render is byte-identical until the topology changes — the SOA serial is
nominal because each zone has exactly one authoritative server and no transfer.
"""

from __future__ import annotations

from typing import Any

from mqlab.dns import (
    ZONES,
    DnsError,
    Record,
    _lab_topo,
    _primary_plane,
    _suffix,
    _zone_of,
    forward_zones,
    reverse_zones,
)

_SERIAL = 1  # one authoritative server per zone, no transfer — serial is nominal
_TTL = 300
_ZONE_DIR = "/etc/bind/zones"
# The lab's enterprise-edge egress to the internet: the vagrant-libvirt NAT gateway
# (libvirt's dnsmasq on the base VM, pinned to the plugin default in
# lab/networks/vagrant-libvirt.xml). infra forwards every non-lab (public) query
# here — internal servers never reach the internet directly (Approach B, #497).
_EGRESS = "192.168.121.1"


def _infra_by_org(topo: dict[str, Any]) -> dict[str, tuple[str, dict[str, Any]]]:
    """``{org -> (host, spec)}`` for the two infra nodes, one per org. Fails loud."""
    nodes = topo.get("nodes") or {}
    out: dict[str, tuple[str, dict[str, Any]]] = {}
    for name in (topo.get("groups") or {}).get("infra") or []:
        spec = nodes.get(name)
        if spec is None:
            raise DnsError(f"infra group references undefined host: {name}")
        org = _org_of(spec)
        if org in out:
            raise DnsError(f"more than one infra node for org {org!r}")
        out[org] = (name, spec)
    for org in ZONES:
        if org not in out:
            raise DnsError(f"no infra node for org {org!r}")
    return out


def _org_of(spec: dict[str, Any]) -> str:
    return "service" if spec.get("org") == "service" else "client"


def _ns_fqdn(host: str, spec: dict[str, Any]) -> str:
    """The zone's NS target — the infra node's primary A record (never the bare
    name, which is a CNAME and so illegal as an NS/SOA target)."""
    nics = spec.get("nics") or {}
    return f"{host}-{_suffix(_primary_plane(host, nics))}.{_zone_of(spec)}"


def _rr(r: Record) -> str:
    value = r.value if r.type == "A" else f"{r.value}."  # A is an address; else a name
    return f"{r.name}. IN {r.type} {value}"


def _zone_file(apex: str, ns: str, records: list[Record]) -> str:
    lines = [
        f"; {apex} — generated by `mqlab dns render`; do not edit",
        f"$TTL {_TTL}",
        f"@ IN SOA {ns}. hostmaster.{apex}. ( {_SERIAL} 3600 600 86400 {_TTL} )",
        f"@ IN NS {ns}.",
        *(_rr(r) for r in records),
    ]
    return "\n".join(lines) + "\n"


def _zone_decl(name: str) -> str:
    return f'zone "{name}" {{ type master; file "{_ZONE_DIR}/{name}.zone"; }};'


def _zone_forward(name: str, peer_ip: str) -> str:
    """A cross-org lab zone this node does not master — forward it to the peer infra
    (which is authoritative), overriding the global egress forwarder for that zone."""
    return f'zone "{name}" {{ type forward; forwarders {{ {peer_ip}; }}; }};'


def _named_options() -> str:
    """Global options: forward every non-authoritative, non-lab (public) query to the
    base-VM egress. Per-zone `forward` stanzas in named.conf.local override this for
    the cross-org lab zones."""
    return (
        "options {\n"
        '    directory "/var/cache/bind";\n'
        "    recursion yes;\n"
        "    allow-query { any; };\n"
        f"    forwarders {{ {_EGRESS}; }};\n"
        "    forward only;\n"
        "    dnssec-validation no;\n"
        "    listen-on { any; };\n"
        "    listen-on-v6 { none; };\n"
        "};\n"
    )


def render(topo: dict[str, Any]) -> dict[str, str]:
    """``{filename -> content}`` for everything the bind-dns role copies:
    ``<zone>.zone`` files plus per-infra ``named.conf.options.<host>`` and
    ``named.conf.local.<host>``."""
    infra = _infra_by_org(topo)
    (client_host, client_spec) = infra["client"]
    (svc_host, svc_spec) = infra["service"]
    client_ns = _ns_fqdn(client_host, client_spec)
    svc_ns = _ns_fqdn(svc_host, svc_spec)

    fwd = forward_zones(topo)
    rev = reverse_zones(topo)
    out: dict[str, str] = {}

    # forward zones — each in its org's authoritative NS
    out[f"{ZONES['client']}.zone"] = _zone_file(ZONES["client"], client_ns, fwd[ZONES["client"]])
    out[f"{ZONES['service']}.zone"] = _zone_file(ZONES["service"], svc_ns, fwd[ZONES["service"]])
    # reverse zones — all mastered by the client-org infra
    for rz, records in rev.items():
        out[f"{rz}.zone"] = _zone_file(rz, client_ns, records)

    # Per-node config. The client infra masters client.com + all reverse zones and
    # forwards service.com to the svc peer; the svc infra masters service.com and
    # forwards client.com + all reverse to the client peer. Everything else (public)
    # goes to the base-VM egress via the global options forwarder — no node ever
    # recurses to the internet directly.
    client_zones = [ZONES["client"], *rev]
    svc_ext = svc_spec["nics"]["net-ext"]
    client_ext = client_spec["nics"]["net-ext"]
    client_local = [_zone_decl(z) for z in client_zones]
    client_local.append(_zone_forward(ZONES["service"], svc_ext))
    svc_local = [_zone_decl(ZONES["service"])]
    svc_local += [_zone_forward(z, client_ext) for z in client_zones]
    out[f"named.conf.local.{client_host}"] = "\n".join(client_local) + "\n"
    out[f"named.conf.local.{svc_host}"] = "\n".join(svc_local) + "\n"
    out[f"named.conf.options.{client_host}"] = _named_options()
    out[f"named.conf.options.{svc_host}"] = _named_options()
    return out


def lab_render() -> dict[str, str]:
    """Render BIND artifacts for the real lab/topology.yaml."""
    return render(_lab_topo())


_RESOLVER_ORDER = ("net-data-a", "net-data-b", "net-ext", "net-mgmt")


def _resolver_ip(
    host: str, spec: dict[str, Any], infra: dict[str, tuple[str, dict[str, Any]]]
) -> str:
    """The nameserver IP ``host`` should query: its org's infra node on the first
    plane they share (data planes first — DNS rides the modeled axis, not the
    Watcher). An infra node resolves via its own BIND on loopback."""
    if any(host == name for name, _ in infra.values()):
        return "127.0.0.1"
    infra_host, infra_spec = infra[_org_of(spec)]
    host_nics = spec.get("nics") or {}
    infra_nics = infra_spec.get("nics") or {}
    for plane in _RESOLVER_ORDER:
        if plane in host_nics and plane in infra_nics:
            return str(infra_nics[plane])
    raise DnsError(f"{host!r} shares no plane with its infra node {infra_host!r}")


def host_dns_facts(topo: dict[str, Any]) -> dict[str, dict[str, str]]:
    """Per-host resolver + self-identity facts the host-resolver role consumes:
    ``{host -> {resolver, self_ip, fqdn}}``. Interface-less hosts are skipped."""
    infra = _infra_by_org(topo)
    out: dict[str, dict[str, str]] = {}
    for host, spec in (topo.get("nodes") or {}).items():
        nics = spec.get("nics") or {}
        if not nics:
            continue
        primary = _primary_plane(host, nics)
        out[host] = {
            "resolver": _resolver_ip(host, spec, infra),
            "self_ip": str(nics[primary]),
            "fqdn": f"{host}.{_zone_of(spec)}",
        }
    return out


def lab_host_dns_facts() -> dict[str, dict[str, str]]:
    """Host DNS facts for the real lab/topology.yaml."""
    return host_dns_facts(_lab_topo())
