"""Console-script entry point with a stale-venv bootstrap guard (#1063).

`mqlab` is installed as `mqlab.launcher:main` (pyproject `[project.scripts]`).
This module is deliberately thin and syntactically conservative: it must stay
parseable by an interpreter *older* than the one the package now requires, so a
`.venv` seeded before a Python-version bump — and therefore unable to parse the
package's newer syntax — yields an actionable remediation instead of a raw
`SyntaxError` traceback.

Why a separate launcher, and not the in-CLI guard alone: the self-healing
`uv sync` (`venvsync.ensure_venv_current`) lives inside `mqlab.cli`, whose
module-level imports pull in the whole package. If any imported module uses
syntax the stale interpreter cannot parse, importing `cli` dies *before* the
guard's call site is ever reached — the guard cannot rescue the venv whose
staleness breaks the import of the module that contains the guard's own call.
This launcher runs before that import graph and does not itself import any of
the modules that might be too new to parse, so it survives to give guidance.

Scope of the rescue: the console script is regenerated by `uv sync`, so this
guard protects against *future* version skew once a 3.14 venv is in place. A
venv so stale it cannot parse this launcher is beyond self-rescue by design —
that is what `uv sync` / `scripts/setup` are for.
"""

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable

# Minimum Python feature version the package's source requires. Kept consistent
# with `requires-python` in pyproject.toml and `.python-version` by
# tests/test_python_pin.py. An import-time SyntaxError under an interpreter
# older than this is a stale venv (not a code bug), and is the only case this
# launcher converts into remediation rather than re-raising.
MIN_PYTHON = (3, 14)


def _import_cli_main() -> Callable[[], None]:
    from mqlab.cli import main as cli_main

    return cli_main


def _stale_venv_message(version: tuple[int, ...]) -> str:
    running = ".".join(str(part) for part in version[:3])
    required = ".".join(str(part) for part in MIN_PYTHON)
    return (
        f"mqlab: the .venv is stale for the pinned Python — its interpreter "
        f"(Python {running}) is too old to parse the current code "
        f"(needs >= {required}).\n"
        f"mqlab: rebuild the venv against the pinned interpreter:\n"
        f"mqlab:     uv sync          # or: ./scripts/setup\n"
    )


def main(
    *,
    import_cli_main: Callable[[], Callable[[], None]] = _import_cli_main,
    version_info: tuple[int, ...] = sys.version_info[:3],
    stderr: Callable[[str], object] = sys.stderr.write,
) -> None:
    """Run the mqlab CLI, guarding the stale-venv bootstrap trap (#1063).

    Import the CLI (which drags in the whole package). If that raises a
    `SyntaxError` *and* the running interpreter predates `MIN_PYTHON`, the venv
    is stale for the pin: surface remediation and exit non-zero. On any other
    interpreter the SyntaxError is a genuine code bug and is re-raised unmasked.
    The `import_cli_main`/`version_info`/`stderr` seams are injected in tests.
    """
    try:
        cli_main = import_cli_main()
    except SyntaxError:
        if tuple(version_info[:2]) < MIN_PYTHON:
            stderr(_stale_venv_message(tuple(version_info)))
            raise SystemExit(1) from None
        raise
    cli_main()
